// src/Certificates.tsx
import React from "react";
import { Certificate } from "./types";

export const Certificates: React.FC<{ certificates: Certificate[] }> = ({
  certificates,
}) => (
  <>
    {certificates.length > 0 && (
      <section className="section">
        <header>
          <h2 className="section-title">Certificates</h2>
        </header>
        <section id="certificates">
          {certificates.map((certificate, index) => (
            <section key={index} className="certificate-item">
              <header className="clear">
                {certificate.date && (
                  <div className="date">{certificate.date}</div>
                )}
                <div className="header-left">
                  {certificate.name && (
                    <div className="name">{certificate.name}</div>
                  )}
                  {certificate.issuer && (
                    <div className="issuer">{certificate.issuer}</div>
                  )}
                </div>
              </header>
              <div className="item">
                {certificate.url && (
                  <span className="url">
                    <span className="fas fa-external-link-alt"></span>
                    <a
                      target="_blank"
                      rel="noopener noreferrer"
                      href={certificate.url}
                    >
                      {certificate.url}
                    </a>
                  </span>
                )}
              </div>
            </section>
          ))}
        </section>
      </section>
    )}
  </>
);

// src/components/Certificates.svelte
<script>
  import { t } from '../utils/helpers.ts';
  import { getDateHelpers } from '../utils/date-helpers.ts';

  let { certificates = [], language = 'en-gb' } = $props();

  const { MY } = getDateHelpers(language);
</script>

{#if certificates?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.certificates')} <span class="item-count">({certificates.length})</span></h2>
    </header>
    <section id="certificates">
      {#each certificates as cert}
        <section class="certificate-item">
          <header class="clear">
            {#if cert.date}
              <div class="date">{MY(cert.date)}</div>
            {/if}
            <div class="header-left">
              {#if cert.name}
                <div class="name">{cert.name}</div>
              {/if}
              {#if cert.issuer}
                <div class="issuer">{cert.issuer}</div>
              {/if}
            </div>
          </header>
          <div class="item">
            {#if cert.url}
              <span class="url">
                <span class="fa-solid fa-up-right-from-square"></span>
                <a target="_blank" href={cert.url}>{cert.url}</a>
              </span>
            {/if}
          </div>
        </section>
      {/each}
    </section>
  </section>
{/if}
