// src/Education.tsx
import React from "react";
import { EducationProps } from "./types";

export const Education: React.FC<{ education: EducationProps[] }> = ({
  education,
}) => {
  if (!education.length) return null;

  const formatDate = (date: string) => {
    return new Date(date).getFullYear();
  };

  return (
    <section className="section">
      <header>
        <h2 className="section-title">
          Education <span className="item-count">({education.length})</span>
        </h2>
      </header>

      <section id="education">
        {education.map((edu, index) => (
          <section className="education-item" key={index}>
            <header className="clear">
              <div className="date">
                {edu.startDate && (
                  <span className="startDate">{formatDate(edu.startDate)}</span>
                )}
                {edu.endDate ? (
                  <span className="endDate"> - {formatDate(edu.endDate)}</span>
                ) : (
                  <span className="endDate"> - Current</span>
                )}
              </div>
              <div className="header-left">
                {edu.studyType && (
                  <div className="studyType">{edu.studyType}</div>
                )}
                {edu.area && <div className="area">{edu.area}</div>}
                {edu.institution && (
                  <div className="institution">{edu.institution}</div>
                )}
              </div>
            </header>

            {edu.courses?.length && (
              <ul className="courses">
                {edu.courses.map((course, i) => (
                  <li key={i}>{course}</li>
                ))}
              </ul>
            )}

            <div className="item">
              {edu.score && (
                <div className="gpa">
                  <strong> Grade:</strong> <span>{edu.score}</span>
                </div>
              )}
            </div>
          </section>
        ))}
      </section>
    </section>
  );
};

// src/components/Education.svelte
<script>
  import { paragraphSplit, t } from '../utils/helpers.ts';
  import DateRange from './DateRange.svelte';

  let { education = [], language = 'en-gb' } = $props();
</script>

{#if education?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.education')} <span class="item-count">({education.length})</span></h2>
    </header>
    <section id="education">
      {#each education as edu, index}
        <section class="education-item">
          {#if edu.summary}
            <label for="education-item-{index}"></label>
          {/if}
          <header class="clear">
            <DateRange startDate={edu.startDate} endDate={edu.endDate} {language} />
            <div class="header-left">
              {#if edu.studyType}
                <div class="studyType">{edu.studyType}</div>
              {/if}
              {#if edu.area}
                <div class="area">{edu.area}</div>
              {/if}
              {#if edu.institution}
                <div class="institution">
                  {#if edu.url}
                    <a target="_blank" href={edu.url}>{edu.institution}</a>
                  {:else}
                    {edu.institution}
                  {/if}
                </div>
              {/if}
            </div>
          </header>

          {#if edu.location}
            <span class="location">
              <span class="fa-solid fa-location-dot"></span>
              {#if edu.location.city}
                <span class="city">{edu.location.city}</span>
              {/if}
              {#if edu.location.countryCode}
                <span class="countryCode">({edu.location.countryCode})</span>
              {/if}
              {#if edu.location.region}
                <span class="region">{edu.location.region}</span>
              {/if}
            </span>
          {/if}

          {#if edu.courses?.length}
            <ul class="courses">
              {#each edu.courses as course}
                <li>{course}</li>
              {/each}
            </ul>
          {/if}

          <div class="item">
            {#if edu.gpa}
              <div class="gpa">
                <strong> Grade:</strong> <span>{edu.gpa}</span>
              </div>
            {/if}
            {#if edu.summary}
              <div class="summary">{@html paragraphSplit(edu.summary)}</div>
            {/if}
          </div>
        </section>
      {/each}
    </section>
  </section>
{/if}
