// src/Languages.tsx
import React from "react";
import { Language } from "./types";

export const Languages: React.FC<{ languages: Language[] }> = ({
  languages,
}) => (
  <>
    {languages.length && (
      <section className="section">
        <header>
          <h2 className="section-title">Languages</h2>
        </header>
        <section id="languages">
          {languages.map((language, index) => (
            <div key={index} className="display">
              {language.language && (
                <h3 className="language">{language.language}</h3>
              )}
              <div className="item">
                {language.fluency && (
                  <div
                    className={`level fluency ${language.fluency.toLowerCase()}`}
                  >
                    <em>{language.fluency}</em>
                    <div className="bar"></div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </section>
      </section>
    )}
  </>
);

// src/components/Languages.svelte
<script>
  import { normalizeLevel, t } from '../utils/helpers.ts';

  let { languages = [] } = $props();
</script>

{#if languages?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.languages')} <span class="item-count">({languages.length})</span></h2>
    </header>
    <section id="languages">
      {#each languages as lang}
        <div class="display">
          {#if lang.language}
            <h3 class="language">{lang.language}</h3>
          {/if}
          <div class="item">
            {#if lang.fluency}
              <div class="level fluency {normalizeLevel(lang.fluency)}">
                {#if lang.fluencyDisplay}
                  <em>{lang.fluencyDisplay}</em>
                {:else}
                  <em>{lang.fluency}</em>
                {/if}
                <div class="bar"></div>
              </div>
            {/if}
          </div>
        </div>
      {/each}
    </section>
  </section>
{/if}
