// src/References.tsx
import React from "react";
import { Reference } from "./types";

export const References: React.FC<{ references: Reference[] }> = ({
  references,
}) =>
  references.length ? (
    <section className="section">
      <header>
        <h2 className="section-title">References</h2>
      </header>
      <section id="references">
        {references.map((reference, index) => (
          <div className="item" key={index}>
            {reference.reference && (
              <blockquote className="reference">
                &#8220;&#32;{reference.reference}&#32;&#8221;
              </blockquote>
            )}
            {reference.name && <div className="name">{reference.name}</div>}
          </div>
        ))}
      </section>
    </section>
  ) : null;

// src/components/References.svelte
<script>
  import { t } from '../utils/helpers.ts';

  let { references = [] } = $props();
</script>

{#if references?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.references')} <span class="item-count">({references.length})</span></h2>
    </header>
    <section id="references">
      {#each references as ref}
        <div class="item">
          {#if ref.reference}
            <blockquote class="reference">&#8220;&#32;{ref.reference}&#32;&#8221;</blockquote>
          {/if}
          {#if ref.name}
            <div class="name">{ref.name}</div>
          {/if}
        </div>
      {/each}
    </section>
  </section>
{/if}
