// src/components/Interests.svelte
<script>
  import { paragraphSplit, t } from '../utils/helpers.ts';

  let { interests = [] } = $props();
</script>

{#if interests?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.interests')} <span class="item-count">({interests.length})</span></h2>
    </header>
    <section id="interests">
      {#each interests as interest}
        <div class="item">
          {#if interest.name}
            <h3 class="name">{interest.name}</h3>
          {/if}
          {#if interest.keywords?.length}
            <ul class="keywords">
              {#each interest.keywords as keyword}
                <li>{keyword}</li>
              {/each}
            </ul>
          {/if}
          {#if interest.summary}
            <div class="summary">{@html paragraphSplit(interest.summary)}</div>
          {/if}
        </div>
      {/each}
    </section>
  </section>
{/if}

// src/Interests.tsx
import React from "react";
import { Interest } from "./types";

export const Interests: React.FC<{ interests: Interest[] }> = ({
  interests,
}) => {
  if (!interests.length) {
    return null;
  }

  return (
    <section className="section">
      <header>
        <h2 className="section-title">Interests</h2>
      </header>
      <section id="interests">
        {interests.map((interest, index) => (
          <div key={index} className="item">
            {interest.name && <h3 className="name">{interest.name}</h3>}
            {interest.keywords?.length && (
              <ul className="keywords">
                {interest.keywords.map((keyword, i) => (
                  <li key={i}>{keyword}</li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </section>
    </section>
  );
};
