// src/components/Projects.svelte
<script>
  import { paragraphSplit, t } from '../utils/helpers.ts';
  import DateRange from './DateRange.svelte';

  let { projects = [], language = 'en-gb' } = $props();
</script>

{#if projects?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.projects')} <span class="item-count">({projects.length})</span></h2>
    </header>
    <section id="projects">
      {#each projects as project, index}
        <section class="project-item">
          {#if project.summary}
            <label for="project-item-{index}"></label>
          {/if}
          {#if project.name}
            <header class="clear">
              <DateRange startDate={project.startDate} endDate={project.endDate} {language} />
              {#if project.name}
                <div class="position">{project.name}</div>
              {/if}
            </header>
          {/if}
          {#if project.location}
            <span class="location">
              <span class="fa-solid fa-location-dot"></span>
              {#if project.location.city}
                <span class="city">{project.location.city},</span>
              {/if}
              {#if project.location.countryCode}
                <span class="countryCode">({project.location.countryCode})</span>
              {/if}
              {#if project.location.region}
                <span class="region">{project.location.region}</span>
              {/if}
            </span>
          {/if}
          {#if project.url}
            <span class="website">
              <span class="fa-solid fa-up-right-from-square"></span>
              <a target="_blank" href={project.url}>{project.url}</a>
            </span>
          {/if}
          {#if project.keywords?.length}
            <ul class="keywords">
              {#each project.keywords as keyword}
                <li>{keyword}</li>
              {/each}
            </ul>
          {/if}
          <div class="item">
            {#if project.description}
              <div class="summary">{@html paragraphSplit(project.description)}</div>
            {/if}
            {#if project.highlights?.length}
              <ul class="highlights">
                {#each project.highlights as highlight}
                  <li>{@html paragraphSplit(highlight)}</li>
                {/each}
              </ul>
            {/if}
          </div>
        </section>
      {/each}
    </section>
  </section>
{/if}

// src/Projects.tsx
import React from "react";
import { Project } from "./types";
import { MY } from "./dateHelpers";

export const Projects: React.FC<{ projects: Project[] }> = ({ projects }) => (
  <>
    {projects.length > 0 && (
      <section className="section">
        <header>
          <h2 className="section-title">
            Projects <span className="item-count">({projects.length})</span>
          </h2>
        </header>
        <section id="projects">
          {projects.map((project, index) => (
            <section className="project-item" key={index}>
              {project.description && (
                <label htmlFor={`project-item-${index}`}></label>
              )}
              {project.name && (
                <header className="clear">
                  {project.name && (
                    <div className="position">{project.name}</div>
                  )}
                  {project.startDate && (
                    <div className="date">
                      <span className="startDate">{MY(project.startDate)}</span>
                      {project.endDate ? (
                        <span className="endDate">- {MY(project.endDate)}</span>
                      ) : (
                        <span className="endDate">- Current</span>
                      )}
                    </div>
                  )}
                </header>
              )}

              {project.url && (
                <span className="website">
                  <span className="fas fa-external-link-alt"></span>
                  <a target="_blank" href={project.url}>
                    {project.url}
                  </a>
                </span>
              )}
              {project.keywords?.length && (
                <ul className="keywords">
                  {project.keywords.map((keyword, index) => (
                    <li key={index}>{keyword}</li>
                  ))}
                </ul>
              )}
              <div className="item">
                {project.description && (
                  <div className="summary">{project.description}</div>
                )}
                {project.highlights?.length && (
                  <ul className="highlights">
                    {project.highlights.map((highlight, index) => (
                      <li key={index}>{highlight}</li>
                    ))}
                  </ul>
                )}
              </div>
            </section>
          ))}
        </section>
      </section>
    )}
  </>
);
