// src/components/Skills.svelte
<script>
  import { toLowerCase, t } from '../utils/helpers.ts';

  let { skills = [] } = $props();
</script>

{#if skills?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.skills')}</h2>
    </header>
    <section id="skills">
      {#each skills as skill}
        <div class="item">
          {#if skill.name}
            <h3 class="name">{skill.name}</h3>
          {/if}
          {#if skill.level}
            <div class="level {toLowerCase(skill.level)}">
              {#if skill.levelDisplay}
                <em>{skill.levelDisplay}</em>
              {:else}
                <em>{skill.level}</em>
              {/if}
              <div class="bar"></div>
            </div>
          {/if}
          {#if skill.keywords?.length}
            <ul class="keywords">
              {#each skill.keywords as keyword}
                <li>{keyword}</li>
              {/each}
            </ul>
          {/if}
        </div>
      {/each}
    </section>
  </section>
{/if}

// src/Skills.tsx
import React from "react";
import { Skill } from "./types";

export const Skills: React.FC<{ skills: Skill[] }> = ({ skills }) =>
  skills.length > 0 ? (
    <section className="section">
      <header>
        <h2 className="section-title">Skills</h2>
      </header>
      <section id="skills">
        {skills.map((skill) => (
          <div className="item">
            {skill.name && <h3 className="name">{skill.name}</h3>}
            {skill.level && (
              <div className={`level ${skill.level.toLowerCase()}`}>
                <em>{skill.level}</em>
                <div className="bar"></div>
              </div>
            )}
            {skill.keywords?.length && (
              <ul className="keywords">
                {skill.keywords.map((keyword, index) => (
                  <li key={index}>{keyword}</li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </section>
    </section>
  ) : null;
