// src/components/Volunteer.svelte
<script>
  import { paragraphSplit, t } from '../utils/helpers.ts';
  import DateRange from './DateRange.svelte';

  let { volunteer = [], language = 'en-gb' } = $props();
</script>

{#if volunteer?.length}
  <section class="section">
    <header>
      <h2 class="section-title">{t('resume.volunteer')} <span class="item-count">({volunteer.length})</span></h2>
    </header>
    <section id="volunteer">
      {#each volunteer as vol, index}
        <section class="volunteer-item">
          {#if vol.organization}
            {#if vol.summary}
              <label for="volunteer-item-{index}"></label>
            {/if}
            <header class="clear">
              <DateRange startDate={vol.startDate} endDate={vol.endDate} {language} />
              <div class="header-left">
                {#if vol.position}
                  <div class="position">{vol.position}</div>
                {/if}
                <div class="organization">
                  {#if vol.url}
                    <a target="_blank" href={vol.url}>{vol.organization}</a>
                  {:else if vol.website}
                    <a target="_blank" href={vol.website}>{vol.organization}</a>
                  {:else}
                    {vol.organization}
                  {/if}
                </div>
              </div>
            </header>
          {/if}
          {#if vol.location}
            <span class="location">
              <span class="fa-solid fa-location-dot"></span>
              {#if vol.location.city}
                <span class="city">{vol.location.city},</span>
              {/if}
              {#if vol.location.countryCode}
                <span class="countryCode">({vol.location.countryCode})</span>
              {/if}
              {#if vol.location.region}
                <span class="region">{vol.location.region}</span>
              {/if}
            </span>
          {/if}
          {#if vol.keywords?.length}
            <ul class="keywords">
              {#each vol.keywords as keyword}
                <li>{keyword}</li>
              {/each}
            </ul>
          {/if}
          <div class="item">
            {#if vol.summary}
              <div class="summary">{@html paragraphSplit(vol.summary)}</div>
            {/if}
            {#if vol.highlights?.length}
              <ul class="highlights">
                {#each vol.highlights as highlight}
                  <li>{@html paragraphSplit(highlight)}</li>
                {/each}
              </ul>
            {/if}
          </div>
        </section>
      {/each}
    </section>
  </section>
{/if}

// src/Volunteer.tsx
import React from "react";
import { Volunteer as VolunteerInterface } from "./types";

interface VolunteerProps {
  volunteer: VolunteerInterface[];
}

export const Volunteer: React.FC<VolunteerProps> = ({ volunteer }) => {
  if (!volunteer.length) {
    return null;
  }

  return (
    <section className="section">
      <header>
        <h2 className="section-title">Volunteer</h2>
      </header>
      <section id="volunteer">
        {volunteer.map((item, index) => (
          <section key={index} className="volunteer-item">
            {item.organization && (
              <>
                {item.summary && (
                  <label htmlFor={`volunteer-item-${index}`}></label>
                )}
                <header className="clear">
                  <div className="date">
                    {item.startDate && (
                      <span className="startDate">
                        {new Date(item.startDate).toLocaleDateString()}
                      </span>
                    )}
                    {item.endDate ? (
                      <span className="endDate">
                        {" "}
                        - {new Date(item.endDate).toLocaleDateString()}
                      </span>
                    ) : (
                      <span className="endDate"> - Current</span>
                    )}
                  </div>
                  <div className="header-left">
                    {item.position && (
                      <div className="position">{item.position}</div>
                    )}
                    <div className="organization">{item.organization}</div>
                  </div>
                </header>
              </>
            )}
            {item.url && (
              <div className="website">
                <span className="fas fa-external-link-alt"></span>
                <a target="_blank" href={item.url}>
                  {item.url}
                </a>
              </div>
            )}

            <div className="item">
              {item.summary && <div className="summary">{item.summary}</div>}
              {item.highlights && item.highlights.length > 0 && (
                <ul className="highlights">
                  {item.highlights.map((highlight, index) => (
                    <li key={index}>{highlight}</li>
                  ))}
                </ul>
              )}
            </div>
          </section>
        ))}
      </section>
    </section>
  );
};
